module.exports = {
    content: [
        './index.html',
        './src/**/*.{js,ts,jsx,tsx,html}'
    ],
    safelist: [
        { pattern: /.*/ }, // Safelist everything for PoC
    ],
    theme: {
        extend: {
            colors: {
                accent: {
                    primary: {
                        weaker: 'var(--color-accent-primary-weaker)',
                        weak:    'var(--color-accent-primary-weak)',
                        default: 'var(--color-accent-primary-default)',
                        strong:  'var(--color-accent-primary-strong)',
                        stronger:'var(--color-accent-primary-stronger)',
                    },
                    warning: {
                        weakest: 'var(--color-accent-warning-weakest)',
                        weaker: 'var(--color-accent-warning-weaker)',
                        weak:    'var(--color-accent-warning-weak)',
                        default: 'var(--color-accent-warning-default)',
                        strong:  'var(--color-accent-warning-strong)',
                        stronger:'var(--color-accent-warning-stronger)',
                        strongest:'var(--color-accent-warning-strongest)',
                    },
                    danger: {
                        weakest: 'var(--color-accent-danger-weakest)',
                        weaker: 'var(--color-accent-danger-weaker)',
                        weak:    'var(--color-accent-danger-weak)',
                        default: 'var(--color-accent-danger-default)',
                        strong:  'var(--color-accent-danger-strong)',
                        stronger:'var(--color-accent-danger-stronger)',
                        strongest:'var(--color-accent-danger-strongest)',
                    },
                    info: {
                        weakest: 'var(--color-accent-info-weakest)',
                        weaker: 'var(--color-accent-info-weaker)',
                        weak:    'var(--color-accent-info-weak)',
                        default: 'var(--color-accent-info-default)',
                        strong:  'var(--color-accent-info-strong)',
                        stronger:'var(--color-accent-info-stronger)',
                        strongest:'var(--color-accent-info-strongest)',
                    },
                    success: {
                        weakest: 'var(--color-accent-success-weakest)',
                        weaker: 'var(--color-accent-success-weaker)',
                        weak:    'var(--color-accent-success-weak)',
                        default: 'var(--color-accent-success-default)',
                        strong:  'var(--color-accent-success-strong)',
                        stronger:'var(--color-accent-success-stronger)',
                        strongest:'var(--color-accent-success-strongest)',
                    },
                    neutral: {
                        weakest: 'var(--color-accent-neutral-weakest)',
                        weaker: 'var(--color-accent-neutral-weaker)',
                        weak:    'var(--color-accent-neutral-weak)',
                        default: 'var(--color-accent-neutral-default)',
                        strong:  'var(--color-accent-neutral-strong)',
                        stronger:'var(--color-accent-neutral-stronger)',
                        strongest:'var(--color-accent-neutral-strongest)',
                    },
                },
                text: {
                    default: 'var(--color-text-default)',
                    secondary: 'var(--color-text-secondary)',
                    subtle: 'var(--color-text-subtle)',
                    inverse: 'var(--color-text-inverse)',
                    link: 'var(--color-text-link)',
                    disabled: 'var(--color-text-disabled)',
                    linkHover: 'var(--color-text-link-hover)',
                    linkSelected: 'var(--color-text-link-selected)',
                },
                icon: {
                    inverse: 'var(--color-icon-inverse)',
                    default: 'var(--color-icon-default)',
                    secondary: 'var(--color-icon-secondary)',
                    subtle: 'var(--color-icon-subtle)',
                    link: 'var(--color-icon-link)',
                    disabled: 'var(--color-icon-disabled)',
                    linkHover: 'var(--color-icon-link-hover)',
                    linkSelected: 'var(--color-icon-link-selected)',
                },
                background: {
                    default: 'var(--color-background-default)',
                    secondary: 'var(--color-background-secondary)',
                    subtle: 'var(--color-background-subtle)',
                    inverse: 'var(--color-background-inverse)',
                    selected: 'var(--color-background-selected)',
                    disabled: 'var(--color-background-disabled)',
                    selectedHover: 'var(--color-background-selected-hover)',
                    disabledAlt: 'var(--color-background-disabled-alt)',
                    selectedDisabled: 'var(--color-background-selected-disabled)',
                },
                border: {
                    default: 'var(--color-border-default)',
                    secondary: 'var(--color-border-secondary)',
                    subtle: 'var(--color-border-subtle)',
                    disabled: 'var(--color-border-disabled)',
                    inverse: 'var(--color-border-inverse)',
                    hover: 'var(--color-border-hover)',
                    active: 'var(--color-border-active)',
                },
                // add other semantic colors as needed
            },
            spacing: { 
                0: '0px',
                1: '4px',
                2: '8px',
                3: '12px',
                4: '16px',
                5: '20px',
                6: '24px',
                7: '28px',
                8: '32px',
                9: '36px',
                10: '40px',
                11: '44px',
                12: '48px',
                14: '56px',
                16: '64px',
                20: '80px',
                24: '96px',
                28: '112px',
                32: '128px',
                36: '144px',
                40: '160px',
                44: '176px',
                48: '192px',
                52: '208px',
                56: '224px',
                60: '240px',
                64: '256px',
                72: '288px',
                80: '320px',
                96: '384px',
            },
            fontSize: { 
                0: '0px',
                1: '4px',
                2: '8px',
                3: '12px',
                4: '16px',
                5: '20px',
                6: '24px',
                7: '28px',
                8: '32px',
                9: '36px',
                10: '40px',
                11: '44px',
                12: '48px',
                14: '56px',
                16: '64px',
                20: '80px',
                24: '96px',
                28: '112px',
                32: '128px',
                36: '144px',
                40: '160px',
                44: '176px',
                48: '192px',
                52: '208px',
                56: '224px',
                60: '240px',
                64: '256px',
                72: '288px',
                80: '320px',
                96: '384px',
            },
            lineHeight: { 
                0: '0px',
                1: '4px',
                2: '8px',
                3: '12px',
                4: '16px',
                5: '20px',
                6: '24px',
                7: '28px',
                8: '32px',
                9: '36px',
                10: '40px',
                11: '44px',
                12: '48px',
                14: '56px',
                16: '64px',
                20: '80px',
                24: '96px',
                28: '112px',
                32: '128px',
                36: '144px',
                40: '160px',
                44: '176px',
                48: '192px',
                52: '208px',
                56: '224px',
                60: '240px',
                64: '256px',
                72: '288px',
                80: '320px',
                96: '384px',
            },
        },
        spacing: {
            0: 0,
            1: 4,
            2: 8,
            3: 12,
            4: 16,
            5: 20,
            6: 24,
            7: 28,
            8: 32,
            9: 36,
            10: 40,
            11: 44,
            12: 48,
            14: 56,
            16: 64,
            20: 80,
            24: 96,
            28: 112,
            32: 128,
            36: 144,
            40: 160,
            44: 176,
            48: 192,
            52: 208,
            56: 224,
            60: 240,
            64: 256,
            72: 288,
            80: 320,
            96: 384
        },
    },
    plugins: [],
};
